### PR TITLE
Fix graph API creating Groups and Users

### PR DESCRIPTION
**Pull request by tmeckel**
This pull request fixes the issue #33 and the corresponding issue with creating groups, where it's not possible to pass the required structs to CreateUser and CreateGroup of the graph API.

Implementation has been tested during the implementation of [PR #205](https://github.com/microsoft/terraform-provider-azuredevops/pull/205) in the Terraform DevOps Provider.

### CODE REVIEW

**Comment by tmeckel** [comment]
@tedchamb any chance to get this merged in the near future? The implementation of the [Terraform resource for creating groups](https://github.com/microsoft/terraform-provider-azuredevops/pull/205) in the Terraform provider for DevOps is based on this PR and currently the build pipeline for my PR over there is failing.

**Comment by tedchamb** [comment]
@tmeckel  , thanks for your contribution!

This file is auto generated, you can tell by the header.  Any changes to the auto generated files need to come from our Go code generator.  The code generator needs to be updated to produce code that handles this case. 

My current thinking is to update the generator to do one of the following:
1. create a separate method for each c# subclass
2. create a property on the args struct for each possible c# subclass, and add a check to ensure only one is populated.

Either of those two approaches would keep things strongly typed.

Timing wise I would probably make the changes over the holidays.

**Comment by tmeckel** [comment]
@tedchamb Thanks for the info and if you could fix the issue with the group and user creation this would be great! But why isn't the Go code generator open source as the generated result so that people can contribute?

**Comment by tmeckel** [comment]
@tedchamb I'll close that PR because as stated above you'll update the code generator.

**Comment by tedchamb** [comment]
@tmeckel , the generator code is in the same repo as the Azure DevOps product code which is not open source.  It has direct dependencies on the Azure DevOps server and client binaries, so it can use reflection to discover the contracts and controllers.  It also uses server route registration to get all the routes.  Due to this we can't easily open source the generator.

**Comment by tmeckel** [comment]
@tedchamb Thank you for the thorough explanation! Much appreciated!

**Pull request closed without merging**
