### PR TITLE
Support for OAuth and Identity Azure SDK

### PR DESCRIPTION
**Pull request by hacker1db**
- Generic Oauth Method to support bringing your own Oauth Token
- Support for Azure.Identity SDK

I took most of this from another PR that has not already been merged and built upon it.

see #105 

This is my first real introduction to GO so if I did something that was different then the "standards" please let me know so I can learn. 

Thanks!

### CODE REVIEW

**Comment by hacker1db** [comment]
@microsoft-github-policy-service agree

**Review by besmiralia — APPROVED** [review]

**Comment by lsuarez5280** [comment]
What's the timeline for completing this pull? I'm very interested in switching to service principal authorization.

**Comment by SimonWahlin** [comment]
I'm also very interested in this feature!
@nechvatalp @besmiralia @hacker1db : Any idea of if and when this can be completed?

**Comment by hacker1db** [comment]
I have had this PR open for a while and still no response or feedback, it's out of my hands.

**Comment by tmeckel** [comment]
@hacker1db @SimonWahlin nobody at Microsoft really cares about the AzDO GO API. This repo should be considered dead. Even if it's the base for the AzDO Terraform Provider. 

The OAuth Service Principal Authentication in PR https://github.com/microsoft/terraform-provider-azuredevops/pull/747/files has been added into the Terraform Provider instead of adding it to this SDK, what would be the very correct way to do so. Because everyone would benefit from it, not only the Terraform provider.

But you can imagine why the people on the provider decided it to do it isolated in the provider: this repo is dead ☠☠

**Comment by hacker1db** [comment]
Can we please mark the project as such before others keep trying to contribute to a dead project? Thank you.

**Comment by hacker1db** [comment]
Closing per comment -> https://github.com/microsoft/azure-devops-go-api/pull/141#issuecomment-2066418999

**Pull request closed without merging**
